### ISSUE TITLE
Service account, cluster role and cluster role binding still remain

### ISSUE THREAD

**Issue by tippy3** [falcosecurity/deploy-kubernetes#124]
**Describe the bug**

Service account, cluster role and cluster role binding were removed in [v4.0.0](https://github.com/falcosecurity/charts/blob/master/charts/falco/BREAKING-CHANGES.md#400) but still remain in [kubernetes/falco/templates](https://github.com/falcosecurity/deploy-kubernetes/tree/main/kubernetes/falco/templates).

As far as I see [Prowjob](https://github.com/falcosecurity/test-infra/blob/master/images/update-falco-k8s-manifests/entrypoint.sh) and #101, those files need to be removed manually?

**How to reproduce it**

**Expected behaviour**

They are removed from this repository.

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by leogr** [comment]
Hey @tippy3 

Good catch, thank you! 

> Service account, cluster role and cluster role binding were removed in [v4.0.0](https://github.com/falcosecurity/charts/blob/master/charts/falco/BREAKING-CHANGES.md#400) but still remain in [kubernetes/falco/templates](https://github.com/falcosecurity/deploy-kubernetes/tree/main/kubernetes/falco/templates).

They were all removed. Anyway just, the service account was re-introduced in [v4.0.1](https://github.com/falcosecurity/charts/blob/master/charts/falco/CHANGELOG.md#v410) 

@alacuku can you let us know if we should keep the service account template? (I guess so, asking for confirmation)

> As far as I see [Prowjob](https://github.com/falcosecurity/test-infra/blob/master/images/update-falco-k8s-manifests/entrypoint.sh) and https://github.com/falcosecurity/deploy-kubernetes/pull/101, those files need to be removed manually?

Yes, it looks like the script does not handle the removal (cc @ maxgio92), so we need to remove them manually.

@tippy3, would you like to open a PR once we confirm which files need to be removed?

**Comment by alacuku** [comment]
In the next release of the charts for Falco 0.38 we will introduce a new `role` & `roleBinding`. Let's wait until Falco 0.38 is out and then update the templates.

**Comment by tippy3** [comment]
I got it and I will wait. Thank you!
